sudo: required
services:
  - docker

before_install:
  - docker build -t eladmz/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true eladmz/react-test npm run test

after_success:
  - docker build -t eladmz/multi-client ./client
  - docker build -t eladmz/multi-nginx ./nginx
  - docker build -t eladmz/multi-server ./server
  - docker build -t eladmz/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push eladmz/multi-client
  - docker push eladmz/multi-nginx
  - docker push eladmz/multi-server
  - docker push eladmz/multi-worker
